spring:
  application:
    name: heimao-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
      embedding:
        options:
          model: ${EMBEDDING_MODEL}
          dimensions: ${DIMENSIONS}
    vectorstore:
      redis:
        initialize-schema: true
        prefix: "doc:"
        # 定义元数据字段及其类型，Spring AI 会据此初始化 Redis Schema
        metadata-fields:
          - name: fileName
            path: "$.fileName"
            type: TAG
        index-name: spring-ai-index


  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5506/heimao?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: root
logging:
  level:
    org.springframework.ai: debug
    com.wjh.heimaoai: debug
